"""Customers table

Revision ID: 760ebff64959
Revises: 1b0f370bdb9a
Create Date: 2023-09-03 12:53:59.962667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760ebff64959'
down_revision = '1b0f370bdb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
